### ISSUE TITLE
update to new inkscape API

### ISSUE THREAD

**Issue by martymcguire** [martymcguire/inkscape-unicorn#10]
there are several issues
- units are a thing that throw errors
- other stuff
- also, testing a zapier mention for @martymcguire

**Comment by ashwath72** [comment]
I make mini CNC plotter machine at home but this is not Working pls help me i am using Arduino, L293d Motor shield old 2nos DVD drive, Micro Servo Stepper Motor its not working only ones works i am vear happy pls pls pls pls help me Bro

**Comment by martymcguire** [comment]
Hi ashwath72,

Please see #15 for discussion about your motor control issues.

**Comment by martymcguire** [comment]
The particulars of this issue are now well-covered by other open issues, so I am closing this one.
