### ISSUE TITLE
can't save as g.code... why?

### ISSUE THREAD

**Issue by versphere** [martymcguire/inkscape-unicorn#14]
![error](https://cloud.githubusercontent.com/assets/24512208/21083370/da6142d2-c029-11e6-8fcd-30750ebb8549.png)

**Comment by versphere** [comment]
why i get this error when i want to save as g.code

**Comment by martymcguire** [comment]
HI versphere,

First, please make sure that you fully followed the installation instructions. That error usually indicates that some of the files for the extension are missing. You need to copy the entire contents of the `src/` folder to your Inkscape's extensions folder, including unicorn.inx, unicorn.py, and the unicorn/ folder with all of it's files.

**Comment by MrFranks** [comment]
I have tried this on the 32 and 64bit i get the same error on both applications. I followed the install instruction ant least 12 time now. Any ideas?


Traceback (most recent call last):

  File "unicorn.py", line 108, in <module>

    e.affect()

  File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 268, in affect

    self.effect()

  File "unicorn.py", line 102, in effect

    parser.parse()

  File "C:\Program Files (x86)\Inkscape\share\extensions\unicorn\svg_parser.py", line 230, in parse

    self.svgWidth = self.getLength('width', 354) * 0.28222

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

**Comment by martymcguire** [comment]
Please make sure that your SVG file has units set in the Document Properties. px or mm should work.

**Comment by MrFranks** [comment]
Thanks for the quick reply but its still a no, I  also read that fix on the thingiverse forum.[http://www.thingiverse.com/thing:5986/#comments]  Ah well I will try a full install again tomorrow and see if I can get it to work. please let me know if you think of another way around this darn error. 

Thanks for your time

**Comment by MrFranks** [comment]
Uninstalled and started clean with 32 bit. Worked first try this morning :). Also made sure settings where set to px for measurements.
Thanks for the help.

**Comment by martymcguire** [comment]
Excellent! Glad you got it working. I'll close this issue, now.
