### ISSUE TITLE
Only my x-axis moves 

### ISSUE THREAD

**Issue by ballethorsoe** [martymcguire/inkscape-unicorn#15]
Hi,
Im doing a project at school and our cnc works fine when other people make a .gcode drawing as path but when i make one, only the x-axis moves. ( https://www.youtube.com/watch?v=2VFOU-WUQIY&t ) This is how we made our cnc. Please get back to me as quick as possible :-)

**Comment by martymcguire** [comment]
Hi ballethorsoe,

It may help to compare your Inkscape extensions directory with other students who are generating working G-Code.

Another thing to try is to make sure that your document units for your SVG are set to "px".

Unfortunately I don't know how much I can help. This extension was only designed to be used with a Cupcake CNC with the Unicorn drawing attachment.

**Comment by ballethorsoe** [comment]
We got it working. Thanks :)
