### ISSUE TITLE
AttributeError: 'module' object has no attribute 'unittouu'

### ISSUE THREAD

**Issue by K00d** [martymcguire/inkscape-unicorn#23]
Please help me: I can’t save my drawing. I converted all objects to Paths before attempting to save as G-Code. Brothers2000 solved this problem but he did’n say how. I use Windows Home 10 and Inkscape version 0.92.2 

This is the error report:

Traceback (most recent call last):
  File "servo.py", line 3172, in <module>
    e.affect()     
  File "inkex.py", line 283, in affect
    self.effect()
  File "servo.py", line 3156, in effect
    self.orientation( self.layers[min(0,len(self.layers)-1)] )        
  File "servo.py", line 3085, in orientation
    doc_height = inkex.unittouu(self.document.getroot().get('height'))
AttributeError: 'module' object has no attribute 'unittouu'”

**Comment by martymcguire** [comment]
Hi K00d,

You are the second person to bring this up in a couple of days. This repository contains no file named "servo.py" and is not the source of this error.

If you Google for the line causing this error, there are some results that may help. Please see #22.
