### ISSUE TITLE
ican't save any image as a G-code file 

### ISSUE THREAD

**Issue by charith12** [martymcguire/inkscape-unicorn#26]
![img_20171216_202438](https://user-images.githubusercontent.com/30438939/34071726-b6b887f6-e2a0-11e7-9e20-33b6b5d935d4.jpg)

File -> Save As -> Save As Type                                                                                                                                                                                   
Save As Type dialogue box is not showing G-CODE file format

**Comment by martymcguire** [comment]
Hi @charith12,

This usually occurs when the `unicorn.inx` file and the `unicorn` folder are not installed in your Inkscape extensions folder, or perhaps have file permissions set that prevents them from being read by Inkscape.

Please double check the installation instructions and verify that the extension files are where Inkscape can find them.

Hope that helps! I'm closing this for now but feel free to re-open if you can verify the file locations and are still seeing the issue.
