### ISSUE TITLE
issue while generating g-code

### ISSUE THREAD

**Issue by neelji** [martymcguire/inkscape-unicorn#30]
![untitled](https://user-images.githubusercontent.com/36640935/36389649-df3b5fb6-15c5-11e8-943f-fb7feb597edc.jpg)

**Comment by martymcguire** [comment]
Hi @neelji,

The error in that screenshot appears to be coming from a "servo.py", which is not part of this extension.

**Comment by neelji** [comment]
here is the complete message
![untitled12](https://user-images.githubusercontent.com/36640935/36390443-122eeaca-15c9-11e8-82bb-158a98cd78dc.png)
can you please explain the solution, actually i am very new user

**Comment by martymcguire** [comment]
hi @neelji,

Thank you for the extra details.

Unfortunately, as I said before, this error is occurring in code that is not a part of this project.

I am afraid that I cannot help you here.
